In [73]:
cd /data/trungnv/Object_Detection/YOLOv5/traindata_car/labels/val/

/data/trungnv/Object_Detection/YOLOv5/traindata_car/labels/val


In [38]:
import sys
import os
import csv
import numpy as np
import scipy.io as sio

In [51]:
mat_file = 'cars_test_annos_withlabels.mat'
# csv_file = 'cars_train_annos.csv'

In [74]:
mat = sio.loadmat(mat_file)

for annotation in mat['annotations'][0]:
    cls = np.squeeze(annotation['class']).tolist()
    x1 = np.squeeze(annotation['bbox_x1']).tolist()
    y1 = np.squeeze(annotation['bbox_y1']).tolist()
    x2 = np.squeeze(annotation['bbox_x2']).tolist()
    y2 = np.squeeze(annotation['bbox_y2']).tolist()
    fname = np.squeeze(annotation['fname']).tolist()
    fname = fname[0:-4] + '.txt'
#     np.savetxt(fname, [cls,x1,y1,x2,y2], delimiter=',')

In [84]:
np.array([cls, x1, y1, x2, y2])

array([ 32,  77,  73, 506, 380])

In [20]:
mat['annotations'][0]

array([(array([[30]], dtype=uint8), array([[52]], dtype=uint8), array([[246]], dtype=uint8), array([[147]], dtype=uint8), array(['00001.jpg'], dtype='<U9')),
       (array([[100]], dtype=uint8), array([[19]], dtype=uint8), array([[576]], dtype=uint16), array([[203]], dtype=uint8), array(['00002.jpg'], dtype='<U9')),
       (array([[51]], dtype=uint8), array([[105]], dtype=uint8), array([[968]], dtype=uint16), array([[659]], dtype=uint16), array(['00003.jpg'], dtype='<U9')),
       ...,
       (array([[33]], dtype=uint8), array([[27]], dtype=uint8), array([[602]], dtype=uint16), array([[252]], dtype=uint8), array(['08039.jpg'], dtype='<U9')),
       (array([[33]], dtype=uint8), array([[142]], dtype=uint8), array([[521]], dtype=uint16), array([[376]], dtype=uint16), array(['08040.jpg'], dtype='<U9')),
       (array([[77]], dtype=uint8), array([[73]], dtype=uint8), array([[506]], dtype=uint16), array([[380]], dtype=uint16), array(['08041.jpg'], dtype='<U9'))],
      dtype=[('bbox_x1', 'O'

In [19]:
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sat Dec 14 14:13:07 2013',
 '__version__': '1.0',
 '__globals__': [],
 'annotations': array([[(array([[30]], dtype=uint8), array([[52]], dtype=uint8), array([[246]], dtype=uint8), array([[147]], dtype=uint8), array(['00001.jpg'], dtype='<U9')),
         (array([[100]], dtype=uint8), array([[19]], dtype=uint8), array([[576]], dtype=uint16), array([[203]], dtype=uint8), array(['00002.jpg'], dtype='<U9')),
         (array([[51]], dtype=uint8), array([[105]], dtype=uint8), array([[968]], dtype=uint16), array([[659]], dtype=uint16), array(['00003.jpg'], dtype='<U9')),
         ...,
         (array([[33]], dtype=uint8), array([[27]], dtype=uint8), array([[602]], dtype=uint16), array([[252]], dtype=uint8), array(['08039.jpg'], dtype='<U9')),
         (array([[33]], dtype=uint8), array([[142]], dtype=uint8), array([[521]], dtype=uint16), array([[376]], dtype=uint16), array(['08040.jpg'], dtype='<U9')),
         (array([[77]],

In [86]:
cd /data/trungnv/Object_Detection/YOLOv5/traindata_car


/data/trungnv/Object_Detection/YOLOv5/traindata_car


In [87]:
np.savetxt('00001.txt',np.array([cls,x1,y1,x2,y2]), delimiter=',')

In [101]:
with open(fname,'w')as output:
    output.write(str(np.array([cls,x1,y1,x2,y2])))

In [89]:
x = np.loadtxt('00001.txt')
x[1]

77.0

In [38]:
with open(csv_file, 'w') as csvfile:
    csvwriter = csv.writer(csvfile)
    csvwriter.writerow(['bbox_x1','bbox_y1','bbox_x2','bbox_y2','class','fname'])
#     csvwriter.writerow(['bbox_x1','bbox_y1','bbox_x2','bbox_y2','class','fname'])

In [16]:
# mat_file = sys.argv[1]
# csv_file = sys.argv[2]

with open(csv_file, 'w') as csvfile:

    mat = sio.loadmat(mat_file)

    for annotation in mat['annotations'][0]:
#         cls = np.squeeze(annotation['class'])
        x1 = np.squeeze(annotation['bbox_x1'])
        y1 = np.squeeze(annotation['bbox_y1'])
        x2 = np.squeeze(annotation['bbox_x2'])
        y2 = np.squeeze(annotation['bbox_y2'])
        fname = np.squeeze(annotation['fname']).tolist()
        fname = fname[0:-4]
        np.savetxt(fname, [x1,y1,x2,y2])


ValueError: no field of name class

In [60]:
cd /data/trungnv/Object_Detection/YOLOv5/car_devkit/


/data/trungnv/Object_Detection/YOLOv5/car_devkit


In [59]:

mat = sio.loadmat(mat_file)

for annotation in mat['annotations'][0]:

    cls = np.squeeze(annotation['class'])
    x1 = np.squeeze(annotation['bbox_x1'])
    y1 = np.squeeze(annotation['bbox_y1'])
    x2 = np.squeeze(annotation['bbox_x2'])
    y2 = np.squeeze(annotation['bbox_y2'])
    fname = np.squeeze(annotation['fname']).tolist()
    fname = fname[0:-4]
    cd labels
    np.savetxt(fname, [cls, x1, y1, x2, y2], delimiter=',')
#     print(fname)
#     print(type(fname))

#     csvwriter.writerow([fname, cls, x1, y1, x2, y2])

FileNotFoundError: [Errno 2] No such file or directory: 'cars_train_annos.mat'

In [24]:
fname = '0001.jpg'

fname = fname[0:-4] + '.txt'
fname

# def convert_fname(fname):
#     fname = fname[0:end-4]
#     return fname

# convert_fname('0001.jpg')

'0001.txt'